// src/pages/Admin/Devices/index.tsx
import { useState } from 'preact/hooks';
import { useDevices } from '../../../hooks/useDevices.ts';

export function AllDevices() {
  const { devices, loading, error, register, deleteDevice, formatDate } = useDevices();
  const [pin, setPin] = useState('');
  const [msg, setMsg] = useState<string | null>(null);

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    const result = await register(pin);
    setMsg(result.message);
    if (result.success) {
      setPin('');
    }
  };

  const handleDelete = async (id: number, room: string) => {
    if (!confirm(`Are you sure you want to delete device ${id} (${room})?`)) {
      return;
    }
    const result = await deleteDevice(id);
    setMsg(result.message);
  };

  return (
    <div class="min-h-screen bg-base-200 p-4">
      <div class="max-w-7xl mx-auto">
        <h1 class="text-5xl font-bold text-center mb-8">Devices</h1>
        
        <div class="card bg-base-100 shadow-xl mb-8">
          <div class="card-body items-center text-center">
            <h2 class="card-title">Link a new device</h2>
            <form onSubmit={handleSubmit} class="w-full">
              <div class="join">
                <input
                  class="input validator input-bordered join-item"
                  placeholder="4 Digit pin"
                  pattern="[0-9]{4}"
                  inputMode="numeric"
                  maxLength={4}
                  required
                  value={pin}
                  onInput={(e: Event) => setPin((e.target as HTMLInputElement).value)}
                />
                <button type="submit" class="btn btn-primary join-item rounded-r-m">Link Device</button>
              </div>
              <p class="validator-hint mt-2 text-left">Input must be 4 digit pin containing only numbers.</p>
              {msg && <p class="mt-2 text-left">{msg}</p>}
            </form>
          </div>
        </div>

        <div class="card bg-base-100 shadow-xl">
          <div class="card-body p-0">
            <div class="overflow-x-auto">
              <table class="table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Registration Date</th>
                    <th>Last Seen</th>
                    <th>Lastest Login</th>
                    <th>Room</th>
                    <th>Active Session</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {loading ? (
                    <tr><td colSpan={7}>Loading...</td></tr>
                  ) : error ? (
                    <tr><td colSpan={7}>Error: {error}</td></tr>
                  ) : devices.length === 0 ? (
                    <tr><td colSpan={7}>No devices</td></tr>
                  ) : (
                    devices.map(d => (
                      <tr key={d.id}>
                        <td>{d.id}</td>
                        <td>{formatDate(d.registration_date)}</td>
                        <td>{formatDate(d.last_seen)}</td>
                        <td>{formatDate(d.latest_login)}</td>
                        <td>{d.room}</td>
                        <td>{d.active_session_id || 'None'}</td>
                        <td>
                          <button
                            type="button"
                            class="btn btn-error btn-sm"
                            onClick={() => handleDelete(d.id, d.room)}
                          >
                            Delete
                          </button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/routes/admin/devices/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	let { data }: { data: PageData } = $props();

	let link_device: HTMLDialogElement = $state();
	// icons
	import PencilIcon from 'phosphor-svelte/lib/PencilIcon';
	import LinkIcon from 'phosphor-svelte/lib/LinkIcon';
	import LinkBreakIcon from 'phosphor-svelte/lib/LinkBreakIcon';
</script>

{#if data.devices.success}
	<div class="mx-auto mt-4 max-w-7xl overflow-x-auto">
		<div class="flex items-center">
			<div class="flex-1"></div>
			<div>
				<button class="btn btn-ghost btn-primary">Relink A Device</button>
				<button onclick={() => link_device.showModal()} class="btn btn-soft btn-primary">
					<LinkIcon weight="bold" />
					Link New Device
				</button>
			</div>
		</div>
		<table class="table">
			<!-- head -->
			<thead>
				<tr>
					<th>ID</th>
					<th>Active Session</th>
					<th>Room</th>
					<th>Last Seen</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{#each data.devices.data as device (device.id)}
					<tr>
						<th>{device.id}</th>
						<td>{device.active_session_id ?? 'None'}</td>
						<td>
							<!-- TODO hook up device room edit here -->
							<div class="flex items-center rounded-box bg-base-100 p-2 hover:cursor-pointer">
								<PencilIcon weight="bold" class="mr-2" />
								{device.room ?? 'None'}
							</div>
						</td>
						<td>{device.last_seen}</td>
						<td>
							<form method="POST" action="?/unlink">
								<input type="hidden" name="device_id" value={device.id} />
								<button
									onclick={(e) => {
										if (!confirm('Are you sure?')) e.preventDefault();
									}}
									class="btn btn-ghost btn-error"
								>
									<LinkBreakIcon weight="bold" />
									Unlink
								</button>
							</form>
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>

	<!--Modals -->
	<dialog bind:this={link_device} class="modal modal-bottom sm:modal-middle">
		<div class="modal-box">
			<h3 class="text-lg font-bold">Link a new device</h3>
			<p class="py-4">Please input the pin shown on your device below.</p>
			<form method="POST" action="?/link">
				<input
					name="pin"
					class="validator input"
					type="text"
					pattern="[0-9][0-9][0-9][0-9]"
					inputMode="numeric"
					placeholder="1234"
					required
				/>
				<div class="validator-hint hidden">Please enter a 4 digit pin</div>
				<div class="modal-action">
					<button type="submit" class="btn btn-soft btn-primary">
						<LinkIcon weight="bold" />
						Link
					</button>
				</div>
			</form>
		</div>
		<form method="dialog" class="modal-backdrop">
			<button>close</button>
		</form>
	</dialog>
{:else}
	<p>{data.devices.message}</p>
{/if}
